# Generated by Django 4.2.5 on 2024-03-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
