# Generated by Django 4.2.5 on 2024-03-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_alter_classrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='enter_time',
            field=models.TimeField(verbose_name='enter_time'),
        ),
    ]
